// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function GenerateContext(arg1:main.GenerateContextInput):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListDirectory(arg1:string):Promise<Array<main.FileNode>>;

export function SelectDirectory():Promise<string>;
