name: "Build Test"

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

env:
  GO_VERSION: '1.23'
  NODE_VERSION: '18'

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: 'windows/amd64'
            os: 'windows-latest'
          - name: 'darwin/arm64'
            os: 'macos-latest'

    runs-on: ${{ matrix.platform.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest



      - name: Run Go tests
        run: go test ./...

      - name: Test Wails build
        run: |
          wails build --platform ${{ matrix.platform.name }} --clean 