name: "Build Test"

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

env:
  GO_VERSION: '1.23'
  NODE_VERSION: '18'

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'windows/amd64'
            os: 'windows-latest'
          - name: 'darwin/amd64'
            os: 'macos-latest'

    runs-on: ${{ matrix.platform.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # Linux 特定依赖
      - name: Install Linux dependencies
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Run Go tests
        run: go test ./...

      - name: Test Wails build
        run: |
          wails build --platform ${{ matrix.platform.name }} --clean 